baseURL = "https://haruharuharukichi.github.io/so-thin/"
languageCode = "jp"
title = "My New Hugo Site"
publishDir = "docs"

[[menu.main]]
    name = "COMPONENTS TOP"
    url = "/components/"
    weight = 1
 
[[menu.main]]
    name = "Grid"
    url = "/components/grid/"
    weight = 2
 
[[menu.main]]
    name = "Header"
    url = "/components/header/"
    weight = 3
 
[[menu.main]]
    name = "Navigation"
    url = "/components/navigation/"
    weight = 4
 
[[menu.main]]
    name = "Card"
    url = "/components/card/"
    weight = 5
 
[[menu.main]]
    name = "Button"
    url = "/components/button/"
    weight = 6
 